[package]
name = "THLVetoken"
version = "1.1.0"

[addresses]
thl_vetoken = "07fd500c11216f0fe3095d0c4b8aa4d64a4e2e04f83758462f2b127255643615"
thl_vetoken_deployer = "1bf23f0881f8fa149500ff6b7a047f608967c028a8ad7a2100caa84833ce851d"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "mainnet"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "mainnet"

[dependencies.ResourceSignerPackage]
local = "../resource_signer_package"

[dependencies.ThalaManager]
local = "../thala_manager"